server:
  servlet:
    context-path: /legoShopServices

app:
  datasource:
    customers:
      url: jdbc:mysql://localhost:3306/customers
      username: root
      password: toor
      driver-class-name: com.mysql.cj.jdbc.Driver
    products:
      url: jdbc:mysql://localhost:3306/products
      username: root
      password: toor
      driver-class-name: com.mysql.cj.jdbc.Driver
